### PR TITLE
include the json schema of funder object

### PR DESCRIPTION
**Pull request by sblack-usu**
The funder object was being overwritten as a string in the __modify_schema__ class method.  I looked at the other properties that use __modify_schema__ and they are all strings so this is the only object affected.

### CODE REVIEW

**Comment by sblack-usu** [comment]
@Maurier - The uischema likely needs to be updated as well.  Would you mind taking a look at it?

**Comment by Maurier** [comment]
> @Maurier - The uischema likely needs to be updated as well.  Would you mind taking a look at it?

Got it. I'll taka care of it.

**Comment by sblack-usu** [comment]
eh, this isn't quite fixing it.  I have to move things around a little bit

**Comment by sblack-usu** [comment]
@Maurier - fixed for real this time.

**Comment by Maurier** [comment]
@sblack-usu It looks like the overwrites are removing the `required` specifications in these fields. For example, the resulting schema for this field does not specify the `name` property as `required`.

```
"funder": {
            "title": "Funding Organization",
            "description": "The organization that provided the funding or sponsorship.",
            "type": "object",
            "properties": {
              . . .
            }
          }
```

**Comment by sblack-usu** [comment]
@Maurier - I pushed a fix for the required issue you found.  It injects the whole schema in and then overwrites the title.

**Review by Maurier — APPROVED** [review]
Looks good

**Pull request merged**
